environment = "dev"
region = "us-west-2"
s3_bucket = "amazon-eks-dev-us-west-2"           #Will be used to set backend.tf
s3_folder_project = "application"            #Will be used to set backend.tf
s3_folder_region = "us-west-2"               #Will be used to set backend.tf
s3_folder_type = "state"                     #Will be used to set backend.tf
s3_tfstate_file = "infrastructure.tfstate"   #Will be used to set backend.tf
vpc_id = "vpc-628a311a"
subnet1 = "subnet-0665717f"
subnet2 = "subnet-6e2dca33"
subnet3 = "subnet-9d31aeb6"
cluster_name = "dev-cluster"
instance_type = "m4.large"
asg_max_size = "48" 
asg_min_size = "3"
asg_desired_capacity = "3"
cluster_version = "1.14"
